version: '3.9'

services:
  backend:
    container_name: expense-tracker-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:15
    container_name: expense-tracker-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  prisma-studio:  # ← Fixed indentation - same level as other services
    image: node:20-alpine
    container_name: expense-tracker-studio
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb
    depends_on:
      - postgres
    command: sh -c "npm install && npx prisma generate && npx prisma studio --port 5555 --hostname 0.0.0.0"

volumes:
  pgdata: