services:
  backend:
    container_name: expense-tracker-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      - postgres
    command: npm start
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: expense-tracker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: